version: '3.0'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/tls:/etc/nginx/tls
      - ./public:/public
        #    ports:
        #      - "443:443"
    network_mode: host
    restart: always

  webapp:
    build: ./webapp/go
    environment:
      ISUCON_DB_HOST: mysql
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      ISUCON_ADMIN_HOSTNAME: admin.t.isucon.dev
    ports:
      - "3000:3000"
    links:
      - mysql
      - redis
    volumes:
      - ./webapp:/home/isucon/webapp
      # - tenant_db:/home/isucon/webapp/tenant_db
      - initial_data:/home/isucon/initial_data
      - gopkg:/home/isucon/go/pkg
    tmpfs:
    - /home/isucon/webapp/tenant_db
    init: true
    restart: always

  mysql:
    image: mysql/mysql-server:8.0.31
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./webapp/sql/admin/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    restart: always

  blackauth:
    build: ./webapp/go
    ports:
      - "3001:3001"
    init: true
    restart: always
    volumes:
      - .:/home/isucon
    working_dir: /home/isucon/blackauth
    command:
      - /usr/local/go/bin/go
      - run
      - main.go

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  bench:
    build: ./webapp/go
    stdin_open: true
    tty: true
    environment:
      ISUCON_JWT_KEY_FILE: ./isuports.pem
    volumes:
      - .:/home/isucon
      - tenant_db:/home/isucon/webapp/tenant_db
      - initial_data:/home/isucon/initial_data
      - gopkg:/home/isucon/go/pkg
    network_mode: host
    working_dir: /home/isucon/bench
    command:
      - "bash"
      - "-c"
      - "sleep infinity"

volumes:
  mysql:
  gopkg:
  tenant_db:
  initial_data:
  redis:
